### ISSUE TITLE
docs.laminas.dev is broken. 

### ISSUE THREAD

**Issue by Sandman83** [laminas/laminas.dev#1] opened 2020-02-12 17:13 UTC
see https://github.com/laminas/getlaminas.org/issues/25

**Comment by michalbundyra** [comment] 2020-02-12 17:32
It's not. Check your DNS and check if you can open any *.dev domain, to make sure it is not locked somehow.

**Comment by froschdesign** [comment] 2020-02-12 17:32
Duplicate of https://github.com/laminas/getlaminas.org/issues/25

**Closed by michalbundyra** 2020-02-12 17:32 UTC
Labels: Duplicate
